name: Node Continuous integration
on: push
jobs:
  first-job:
    name: Build Node
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps:
      - name: Check node version
        run: node --version
      - name: Check npm version
        run: npm --version
      - uses: actions/checkout@v2
        name: checkout code
      - run: npm install
        name: install npm to build the app in container
      - run: node app.js
        name: run the app
